### ISSUE TITLE
Audio dropouts when changing parameters

### ISSUE THREAD

**Issue by Orbital5k** [MarkzP/AudioEffectDynamics#2]
Hi Mark,

Just having a playing around with the dynamics effects - the compressor is very nice indeed but I have an issue: 

When changing any of the compression parameters live, the sound mutes then fades back in fairly quickly. Is this intended? I have reviewed the library and can't find the exact place in the code that causes this. Is this intentional? 

Any help would be great, thanks again!

**Comment by Orbital5k** [comment]
I should mention that I am using a teensy 4.0 in case that is relevant.

**Comment by MarkzP** [comment]
Hi Orbital5k,

I’m glad to hear you like this project!
Full disclosure: I more or less stopped maintaining this code, mostly due to hardware reasons - notably, the SGTL5000 lacks the dynamic range needed to really benefit from such processing.

Now to solve your issue, I would start by adding methods to manipulate individual settings. Then, especially with the T4 (which I don’t have yet), I would probably change all floats to double, and recompute the state more often

Also remember to disable audio interrupts while updating parameters

Marc

**Comment by MarkzP** [comment]
Btw, which parameter are you updating live?

**Comment by Orbital5k** [comment]
Hi Marc,

Thank you very much for getting back to me!

Those suggestions sound very sensible as currently if any of the updatable parameters are changed I am calling the entire compression function: 

Ch1_Comp.compression(Ch1_Comp_Thresh, Ch1_Comp_Attack, Ch1_Comp_Release, Ch1_Comp_Ratio, Ch1_Comp_Knee);

I will investigate updating the floats to double precision and splitting out the parameters to be updated individually.

The compressor itself sounds very nice with static settings. I will let you how it goes and add any progress I make to Github,

Thanks again,
Barry

**Comment by MarkzP** [comment]
Hi Barry,

just did a quick fix that might solve the issue
I won't be able to test until much later, let me know if you get a chance to try it

Marc

**Comment by Orbital5k** [comment]
Thanks Marc,

I just tested and everything is working perfectly, thank you! Audio dropouts completely gone. For learning purposes can I ask which part of the code was causing this behaviour?

Thanks again, I really appreciate you taking the time to update the library.

**Comment by MarkzP** [comment]
Ah I see! I edited the file directly in GitHub, and I forgot to disable line endings comparison

I moved these lines from each param update method to the object constructor:

`		gatedb = MIN_DB;
		compdb = MIN_DB;
		limitdb = MIN_DB;
`

Glad to know it works! Closing this issue

Marc
